/**********************************************\
     This file is automatically generated.
 -----------------------------------------------
 To see how this file is produced, please see
    the NightshadeLua/generation/ directory.
\**********************************************/

// ReSharper disable RedundantUsingDirective
// ReSharper disable PartialTypeWithSinglePart
#pragma warning disable CS0649 // Field is never assigned to, and will always have its default value

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace NightshadeLua.Bindings
{
    public unsafe partial struct luaL_Reg
    {
        [NativeTypeName("const char *")]
        public sbyte* name;

        [NativeTypeName("lua_CFunction")]
        public delegate* unmanaged[Cdecl]<lua_State*, int> func;
    }

    public unsafe partial struct luaL_Buffer
    {
        [NativeTypeName("char *")]
        public sbyte* b;

        [NativeTypeName("size_t")]
        public nuint size;

        [NativeTypeName("size_t")]
        public nuint n;

        public lua_State* L;

        [NativeTypeName("__AnonymousRecord_lauxlib_L190_C3")]
        public _init_e__Union init;

        [StructLayout(LayoutKind.Explicit)]
        public unsafe partial struct _init_e__Union
        {
            [FieldOffset(0)]
            public double u;

            [FieldOffset(0)]
            public void* s;

            [FieldOffset(0)]
            [NativeTypeName("long long")]
            public long l;

            [FieldOffset(0)]
            [NativeTypeName("char[1024]")]
            public _b_e__FixedBuffer b;

            [InlineArray(1024)]
            public partial struct _b_e__FixedBuffer
            {
                public sbyte e0;
            }
        }
    }

    public unsafe partial struct luaL_Stream
    {
        [NativeTypeName("FILE *")]
        public void* f;

        [NativeTypeName("lua_CFunction")]
        public delegate* unmanaged[Cdecl]<lua_State*, int> closef;
    }

    public static unsafe partial class Lauxlib
    {
        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_checkversion_(lua_State* L, [NativeTypeName("lua_Number")] double ver, [NativeTypeName("size_t")] nuint sz);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_getmetafield(lua_State* L, int obj, [NativeTypeName("const char *")] sbyte* e);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_callmeta(lua_State* L, int obj, [NativeTypeName("const char *")] sbyte* e);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* luaL_tolstring(lua_State* L, int idx, [NativeTypeName("size_t *")] nuint* len);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_argerror(lua_State* L, int arg, [NativeTypeName("const char *")] sbyte* extramsg);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_typeerror(lua_State* L, int arg, [NativeTypeName("const char *")] sbyte* tname);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* luaL_checklstring(lua_State* L, int arg, [NativeTypeName("size_t *")] nuint* l);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* luaL_optlstring(lua_State* L, int arg, [NativeTypeName("const char *")] sbyte* def, [NativeTypeName("size_t *")] nuint* l);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Number")]
        public static extern double luaL_checknumber(lua_State* L, int arg);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Number")]
        public static extern double luaL_optnumber(lua_State* L, int arg, [NativeTypeName("lua_Number")] double def);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Integer")]
        public static extern long luaL_checkinteger(lua_State* L, int arg);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Integer")]
        public static extern long luaL_optinteger(lua_State* L, int arg, [NativeTypeName("lua_Integer")] long def);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_checkstack(lua_State* L, int sz, [NativeTypeName("const char *")] sbyte* msg);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_checktype(lua_State* L, int arg, int t);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_checkany(lua_State* L, int arg);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_newmetatable(lua_State* L, [NativeTypeName("const char *")] sbyte* tname);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_setmetatable(lua_State* L, [NativeTypeName("const char *")] sbyte* tname);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* luaL_testudata(lua_State* L, int ud, [NativeTypeName("const char *")] sbyte* tname);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* luaL_checkudata(lua_State* L, int ud, [NativeTypeName("const char *")] sbyte* tname);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_where(lua_State* L, int lvl);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_error(lua_State* L, [NativeTypeName("const char *")] sbyte* fmt, __arglist);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_checkoption(lua_State* L, int arg, [NativeTypeName("const char *")] sbyte* def, [NativeTypeName("const char *const[]")] sbyte** lst);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_fileresult(lua_State* L, int stat, [NativeTypeName("const char *")] sbyte* fname);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_execresult(lua_State* L, int stat);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* luaL_alloc(void* ud, void* ptr, [NativeTypeName("size_t")] nuint osize, [NativeTypeName("size_t")] nuint nsize);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_ref(lua_State* L, int t);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_unref(lua_State* L, int t, int @ref);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_loadfilex(lua_State* L, [NativeTypeName("const char *")] sbyte* filename, [NativeTypeName("const char *")] sbyte* mode);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_loadbufferx(lua_State* L, [NativeTypeName("const char *")] sbyte* buff, [NativeTypeName("size_t")] nuint sz, [NativeTypeName("const char *")] sbyte* name, [NativeTypeName("const char *")] sbyte* mode);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_loadstring(lua_State* L, [NativeTypeName("const char *")] sbyte* s);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* luaL_newstate();

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("unsigned int")]
        public static extern uint luaL_makeseed(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Integer")]
        public static extern long luaL_len(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_addgsub(luaL_Buffer* b, [NativeTypeName("const char *")] sbyte* s, [NativeTypeName("const char *")] sbyte* p, [NativeTypeName("const char *")] sbyte* r);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* luaL_gsub(lua_State* L, [NativeTypeName("const char *")] sbyte* s, [NativeTypeName("const char *")] sbyte* p, [NativeTypeName("const char *")] sbyte* r);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_setfuncs(lua_State* L, [NativeTypeName("const luaL_Reg *")] luaL_Reg* l, int nup);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaL_getsubtable(lua_State* L, int idx, [NativeTypeName("const char *")] sbyte* fname);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_traceback(lua_State* L, lua_State* L1, [NativeTypeName("const char *")] sbyte* msg, int level);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_requiref(lua_State* L, [NativeTypeName("const char *")] sbyte* modname, [NativeTypeName("lua_CFunction")] delegate* unmanaged[Cdecl]<lua_State*, int> openf, int glb);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_buffinit(lua_State* L, luaL_Buffer* B);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("char *")]
        public static extern sbyte* luaL_prepbuffsize(luaL_Buffer* B, [NativeTypeName("size_t")] nuint sz);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_addlstring(luaL_Buffer* B, [NativeTypeName("const char *")] sbyte* s, [NativeTypeName("size_t")] nuint l);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_addstring(luaL_Buffer* B, [NativeTypeName("const char *")] sbyte* s);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_addvalue(luaL_Buffer* B);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_pushresult(luaL_Buffer* B);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_pushresultsize(luaL_Buffer* B, [NativeTypeName("size_t")] nuint sz);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("char *")]
        public static extern sbyte* luaL_buffinitsize(lua_State* L, luaL_Buffer* B, [NativeTypeName("size_t")] nuint sz);
    }
}
