/**********************************************\
     This file is automatically generated.
 -----------------------------------------------
 To see how this file is produced, please see
    the NightshadeLua/generation/ directory.
\**********************************************/

// ReSharper disable RedundantUsingDirective
// ReSharper disable PartialTypeWithSinglePart
#pragma warning disable CS0649 // Field is never assigned to, and will always have its default value

using System;
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: GeneratedCode("ClangSharp", "21.1.8.4")]

namespace NightshadeLua.Bindings
{
    public partial struct lua_State
    {
    }

    public unsafe partial struct lua_Debug
    {
        public int @event;

        [NativeTypeName("const char *")]
        public sbyte* name;

        [NativeTypeName("const char *")]
        public sbyte* namewhat;

        [NativeTypeName("const char *")]
        public sbyte* what;

        [NativeTypeName("const char *")]
        public sbyte* source;

        [NativeTypeName("size_t")]
        public nuint srclen;

        public int currentline;

        public int linedefined;

        public int lastlinedefined;

        [NativeTypeName("unsigned char")]
        public byte nups;

        [NativeTypeName("unsigned char")]
        public byte nparams;

        [NativeTypeName("char")]
        public sbyte isvararg;

        [NativeTypeName("unsigned char")]
        public byte extraargs;

        [NativeTypeName("char")]
        public sbyte istailcall;

        public int ftransfer;

        public int ntransfer;

        [NativeTypeName("char[60]")]
        public _short_src_e__FixedBuffer short_src;

        [NativeTypeName("struct CallInfo *")]
        public CallInfo* i_ci;

        public partial struct CallInfo
        {
        }

        [InlineArray(60)]
        public partial struct _short_src_e__FixedBuffer
        {
            public sbyte e0;
        }
    }

    public static unsafe partial class Lua
    {
        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* lua_newstate([NativeTypeName("lua_Alloc")] delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint, void*> f, void* ud, [NativeTypeName("unsigned int")] uint seed);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_close(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* lua_newthread(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_closethread(lua_State* L, lua_State* from);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_CFunction")]
        public static extern delegate* unmanaged[Cdecl]<lua_State*, int> lua_atpanic(lua_State* L, [NativeTypeName("lua_CFunction")] delegate* unmanaged[Cdecl]<lua_State*, int> panicf);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Number")]
        public static extern double lua_version(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_absindex(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gettop(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_settop(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushvalue(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rotate(lua_State* L, int idx, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_copy(lua_State* L, int fromidx, int toidx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_checkstack(lua_State* L, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_xmove(lua_State* from, lua_State* to, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isnumber(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isstring(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_iscfunction(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isinteger(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isuserdata(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_type(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_typename(lua_State* L, int tp);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Number")]
        public static extern double lua_tonumberx(lua_State* L, int idx, int* isnum);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Integer")]
        public static extern long lua_tointegerx(lua_State* L, int idx, int* isnum);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_toboolean(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_tolstring(lua_State* L, int idx, [NativeTypeName("size_t *")] nuint* len);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Unsigned")]
        public static extern ulong lua_rawlen(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_CFunction")]
        public static extern delegate* unmanaged[Cdecl]<lua_State*, int> lua_tocfunction(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_touserdata(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern lua_State* lua_tothread(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const void *")]
        public static extern void* lua_topointer(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_arith(lua_State* L, int op);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawequal(lua_State* L, int idx1, int idx2);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_compare(lua_State* L, int idx1, int idx2, int op);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushnil(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushnumber(lua_State* L, [NativeTypeName("lua_Number")] double n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushinteger(lua_State* L, [NativeTypeName("lua_Integer")] long n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_pushlstring(lua_State* L, [NativeTypeName("const char *")] sbyte* s, [NativeTypeName("size_t")] nuint len);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_pushexternalstring(lua_State* L, [NativeTypeName("const char *")] sbyte* s, [NativeTypeName("size_t")] nuint len, [NativeTypeName("lua_Alloc")] delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint, void*> falloc, void* ud);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_pushstring(lua_State* L, [NativeTypeName("const char *")] sbyte* s);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_pushvfstring(lua_State* L, [NativeTypeName("const char *")] sbyte* fmt, [NativeTypeName("va_list")] sbyte* argp);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_pushfstring(lua_State* L, [NativeTypeName("const char *")] sbyte* fmt, __arglist);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushcclosure(lua_State* L, [NativeTypeName("lua_CFunction")] delegate* unmanaged[Cdecl]<lua_State*, int> fn, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushboolean(lua_State* L, int b);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_pushlightuserdata(lua_State* L, void* p);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_pushthread(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getglobal(lua_State* L, [NativeTypeName("const char *")] sbyte* name);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gettable(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getfield(lua_State* L, int idx, [NativeTypeName("const char *")] sbyte* k);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_geti(lua_State* L, int idx, [NativeTypeName("lua_Integer")] long n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawget(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawgeti(lua_State* L, int idx, [NativeTypeName("lua_Integer")] long n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_rawgetp(lua_State* L, int idx, [NativeTypeName("const void *")] void* p);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_createtable(lua_State* L, int narr, int nrec);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_newuserdatauv(lua_State* L, [NativeTypeName("size_t")] nuint sz, int nuvalue);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getmetatable(lua_State* L, int objindex);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getiuservalue(lua_State* L, int idx, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setglobal(lua_State* L, [NativeTypeName("const char *")] sbyte* name);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_settable(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setfield(lua_State* L, int idx, [NativeTypeName("const char *")] sbyte* k);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_seti(lua_State* L, int idx, [NativeTypeName("lua_Integer")] long n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawset(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawseti(lua_State* L, int idx, [NativeTypeName("lua_Integer")] long n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_rawsetp(lua_State* L, int idx, [NativeTypeName("const void *")] void* p);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_setmetatable(lua_State* L, int objindex);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_setiuservalue(lua_State* L, int idx, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_callk(lua_State* L, int nargs, int nresults, [NativeTypeName("lua_KContext")] nint ctx, [NativeTypeName("lua_KFunction")] delegate* unmanaged[Cdecl]<lua_State*, int, nint, int> k);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_pcallk(lua_State* L, int nargs, int nresults, int errfunc, [NativeTypeName("lua_KContext")] nint ctx, [NativeTypeName("lua_KFunction")] delegate* unmanaged[Cdecl]<lua_State*, int, nint, int> k);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_load(lua_State* L, [NativeTypeName("lua_Reader")] delegate* unmanaged[Cdecl]<lua_State*, void*, nuint*, sbyte*> reader, void* dt, [NativeTypeName("const char *")] sbyte* chunkname, [NativeTypeName("const char *")] sbyte* mode);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_dump(lua_State* L, [NativeTypeName("lua_Writer")] delegate* unmanaged[Cdecl]<lua_State*, void*, nuint, void*, int> writer, void* data, int strip);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_yieldk(lua_State* L, int nresults, [NativeTypeName("lua_KContext")] nint ctx, [NativeTypeName("lua_KFunction")] delegate* unmanaged[Cdecl]<lua_State*, int, nint, int> k);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_resume(lua_State* L, lua_State* from, int narg, int* nres);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_status(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_isyieldable(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setwarnf(lua_State* L, [NativeTypeName("lua_WarnFunction")] delegate* unmanaged[Cdecl]<void*, sbyte*, int, void> f, void* ud);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_warning(lua_State* L, [NativeTypeName("const char *")] sbyte* msg, int tocont);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gc(lua_State* L, int what, __arglist);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_error(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_next(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_concat(lua_State* L, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_len(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("unsigned int")]
        public static extern uint lua_numbertocstring(lua_State* L, int idx, [NativeTypeName("char *")] sbyte* buff);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("size_t")]
        public static extern nuint lua_stringtonumber(lua_State* L, [NativeTypeName("const char *")] sbyte* s);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Alloc")]
        public static extern delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint, void*> lua_getallocf(lua_State* L, void** ud);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_setallocf(lua_State* L, [NativeTypeName("lua_Alloc")] delegate* unmanaged[Cdecl]<void*, void*, nuint, nuint, void*> f, void* ud);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_toclose(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_closeslot(lua_State* L, int idx);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getstack(lua_State* L, int level, lua_Debug* ar);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_getinfo(lua_State* L, [NativeTypeName("const char *")] sbyte* what, lua_Debug* ar);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_getlocal(lua_State* L, [NativeTypeName("const lua_Debug *")] lua_Debug* ar, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_setlocal(lua_State* L, [NativeTypeName("const lua_Debug *")] lua_Debug* ar, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_getupvalue(lua_State* L, int funcindex, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("const char *")]
        public static extern sbyte* lua_setupvalue(lua_State* L, int funcindex, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void* lua_upvalueid(lua_State* L, int fidx, int n);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_upvaluejoin(lua_State* L, int fidx1, int n1, int fidx2, int n2);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void lua_sethook(lua_State* L, [NativeTypeName("lua_Hook")] delegate* unmanaged[Cdecl]<lua_State*, lua_Debug*, void> func, int mask, int count);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: NativeTypeName("lua_Hook")]
        public static extern delegate* unmanaged[Cdecl]<lua_State*, lua_Debug*, void> lua_gethook(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gethookmask(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int lua_gethookcount(lua_State* L);
    }

    /// <summary>Defines the type of a member as it was used in the native signature.</summary>
    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = false, Inherited = true)]
    [Conditional("DEBUG")]
    internal sealed partial class NativeTypeNameAttribute : Attribute
    {
        private readonly string _name;

        /// <summary>Initializes a new instance of the <see cref="NativeTypeNameAttribute" /> class.</summary>
        /// <param name="name">The name of the type that was used in the native signature.</param>
        public NativeTypeNameAttribute(string name)
        {
            _name = name;
        }

        /// <summary>Gets the name of the type that was used in the native signature.</summary>
        public string Name => _name;
    }

    /// <summary>Defines the annotation found in a native declaration.</summary>
    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = true, Inherited = false)]
    [Conditional("DEBUG")]
    internal sealed partial class NativeAnnotationAttribute : Attribute
    {
        private readonly string _annotation;

        /// <summary>Initializes a new instance of the <see cref="NativeAnnotationAttribute" /> class.</summary>
        /// <param name="annotation">The annotation that was used in the native declaration.</param>
        public NativeAnnotationAttribute(string annotation)
        {
            _annotation = annotation;
        }

        /// <summary>Gets the annotation that was used in the native declaration.</summary>
        public string Annotation => _annotation;
    }
}
