/**********************************************\
     This file is automatically generated.
 -----------------------------------------------
 To see how this file is produced, please see
    the NightshadeLua/generation/ directory.
\**********************************************/

// ReSharper disable RedundantUsingDirective
// ReSharper disable PartialTypeWithSinglePart
#pragma warning disable CS0649 // Field is never assigned to, and will always have its default value

using System.Runtime.InteropServices;

namespace NightshadeLua.Bindings
{
    public static unsafe partial class Lualib
    {
        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_base(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_package(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_coroutine(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_debug(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_io(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_math(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_os(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_string(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_table(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int luaopen_utf8(lua_State* L);

        [DllImport("lua", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void luaL_openselectedlibs(lua_State* L, int load, int preload);
    }
}
